### ISSUE TITLE
Missing readme

### ISSUE THREAD

**Issue by janedbal** [Arachne/Codeception#1]
I would like to try this library. Do you plan to provide some quickstart for it?

**Comment by enumag** [comment]
I guess I've tested it enough after almost two years so I'll try to add something. I'm currently busy integrating symfony/form to nette so it will take some time. On the other hand that library will use this one for tests so it will serve as example.

**Comment by marten-cz** [comment]
Can you provide some short examples how to use this extension? I didn't found anything else for nette/codeception. 
Is it possible to submit a form and validate result without need to have presenter?
Or do action on presenter, like submit form, call handle, etc. without the necessity to write the tests like acceptance tests with login screen etc?

**Comment by enumag** [comment]
You don't need this extension for acceptance tests. Acceptance tests work the same as if you go through the browser yourself - which means if you use presenters in your application so will your acceptance tests.

This extension is meant for functional tests - those work by emulating a HTTP request. But still presenter is created in the process.

To test a form without a presenter you should write a unit test and mock the presenter. You don't need this extension for that either but you might want to check out https://github.com/Codeception/MockeryModule (if you use Mockery).

**Comment by enumag** [comment]
I've refactored this package and there is a documentation now if you're still interested: https://github.com/Arachne/Codeception/blob/master/docs/index.md

Beware that it only applies to the master branch (and the future version 0.7.x), not the current 0.6.x stable.
